services:
  # Development environment (your coding workspace)

  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3001:3001
    env_file: 
      .env
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    command: ["yarn", "run", "start:dev"]

  # Frontend webserver
  frontend:
    image: nginx:1-alpine
    depends_on:
      - backend
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  # Database
  db:
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: